# Configuration for GoReleaser
# https://goreleaser.com/

version: 2

project_name: prombackup

env:
  - CGO_ENABLED=0

builds:
  - id: prombackup
    main: ./cmd/prombackup/
    binary: prombackup
    targets: &build_targets
      - go_first_class
    flags: &build_flags
      - -trimpath

  - id: prombackup-server
    main: ./cmd/prombackup-server/
    binary: prombackup-server
    targets: *build_targets
    flags: *build_flags
    ldflags: |
      -s -w
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      -X github.com/prometheus/common/version.Branch={{.Branch}}
      -X github.com/prometheus/common/version.BuildDate={{.Date}}

nfpms:
  - description: Prometheus backup
    maintainer: M. Hanselmann
    bindir: /usr/bin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    contents:
      - src: ./README.md
        dst: /usr/share/doc/prombackup/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/prombackup/LICENSE

archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - ids:
      - prombackup
    use: buildx
    dockerfile: &docker_dockerfile contrib/Dockerfile.goreleaser
    extra_files: &docker_extra_files
      - LICENSE
      - README.md
    image_templates:
      - ghcr.io/hansmi/prombackup:{{.Tag}}
      - ghcr.io/hansmi/prombackup:v{{.Major}}
      - ghcr.io/hansmi/prombackup:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --target=prombackup

  - ids:
      - prombackup-server
    use: buildx
    dockerfile: *docker_dockerfile
    extra_files: *docker_extra_files
    image_templates:
      - ghcr.io/hansmi/prombackup-server:{{.Tag}}
      - ghcr.io/hansmi/prombackup-server:v{{.Major}}
      - ghcr.io/hansmi/prombackup-server:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --target=prombackup-server

changelog:
  groups:
    - title: Dependencies
      regexp: '(?i)^[a-f0-9]{8,64}\s+Bump\s+[-.\w]+/\w.*\sto\s'
      order: 1
    - order: 0

release:
  draft: true
  prerelease: auto

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
